### ISSUE TITLE
Uploading Expedition Lost fails

### ISSUE THREAD

**Issue by Sch3lp** [dsjoerg/ggtracker#13]
Heyo, tried uploading a replay of Expedition Lost but it fails.
There's no error message so I can't tell if I'm doing something wrong, or if there's a simple problem with the parser.

Posting it in this repo because I don't know.
Couldn't find any related issue in here or in the ggpyjobs repo.

**Comment by Sch3lp** [comment]
Might be noteworthy to mention that the match was played with Ryan Schutters GameHeart mod.
But I uploaded a bunch of other replays that were played with that mod and they worked fine.
Among them another one of the new maps (that aren't official yet): Vaani Research Station.

**Comment by dsjoerg** [comment]
Thanks!  Can you send me the replay file?  Or attach it / post a link to it here.

**Comment by Sch3lp** [comment]
I put replay [on dropbox here](https://dl.dropboxusercontent.com/u/677620/Lost%20Expedition.SC2Replay), but after doing that I noticed the name is Lost Expedition instead of Expedition Lost, so it might be a different map than the Blizzard one. I feel stupid not noticing this when we actually played the game. :s

**Comment by dsjoerg** [comment]
Indeed @Sch3lp we are having a parse problem with the map.  This map doesn't appear to have a `enUS.SC2Data\LocalizedData\GameStrings.txt` file inside, whereas all Blizzard maps do.

Currently we are only trying to support Blizzard maps, so I'm going to mark this closed.

**Comment by Sch3lp** [comment]
Rightfully so dear sir.
Thanks for taking the time to reply anyways!
