### ISSUE TITLE
Time calculations incorrect

### ISSUE THREAD

**Issue by kpaleniu** [dsjoerg/ggtracker#16]
The way time is calculated from LotV replays seems to be incorrect. See the following [replay](http://ggtracker.com/matches/6363939). The replay is actually 14:47 long. The graph on the main page says the match lasted 20:43. Is this a known issue?

**Comment by dsjoerg** [comment]
Yes it is, thanks for reporting it.
There are a set of time-related issues that were introduced by 3.0 / LotV, including some bugs inside the SC2 client itself.
We are looking for someone who would like to dig in to the time issues and fix them!

**Comment by Anzumana** [comment]
If the issue is still unresolved when my semester break starts i will take a look.

**Comment by dsjoerg** [comment]
@anzumana great!

**Comment by dmpaul26** [comment]
Made a PR for the time elapsed, what other time issues were introduced by LotV?

**Comment by dsjoerg** [comment]
Here's a summary of the time issues.

Before 3.0, 1.4 Starcraft minutes = 1 real minute = 960 game frames (loops).
After 3.0 / LotV, 1 Starcraft minute = 1 real minute = 960 game frames (loops).

All of GGTracker was built assuming that 960 game frames / loops = 1.4 Starcraft minutes.  So anything related to time in GGTracker is off by a factor of 1.4.  That includes game length, APM and income.

To fix it, broadly, the steps are:
* set up a development environment with the full GGTracker system: sc2reader, ggpyjobs, gg, esdb, ggtracker
* make a targeted set of code changes; maybe 20-30 lines in all
* test that the resulting system works properly

**Comment by dsjoerg** [comment]
If someone is interested in giving this a go, **I can set up a Dockerfile** that has all of sc2reader, ggpyjobs, gg, esdb, ggtracker running so that you can get started more easily and test whatever changes need to be made.

**Comment by agwblack** [comment]
I may be able to help. If you could provide the dev environment then that would be great!

**Comment by dsjoerg** [comment]
OK @agwblack, will do and will ping you when it's ready

**Comment by Anzumana** [comment]
Won't be able to contribute as i was planning on.
Hope you guys can fix it.
Have a good one.

**Comment by gravelweb** [comment]
I use your tool a lot, and am interested in contributing if i can. If you would provide a docker or vagrant dev environment, I'm happy to help speed this along. Getting this issue and the mini-map issue resolved would be totally great.

**Comment by dsjoerg** [comment]
Hey @gravelweb great news.  @nickelsen is working on a vagrant setup, see https://github.com/dsjoerg/ggtracker/pull/20

And your catch about 1v1 vs other game modes makes this one quite killable.

I'll take a look and see if I can narrow down where the bug is happening.

**Comment by gravelweb** [comment]
@dsjoerg That's great! A vagrant setup would be really encouraging for new devs on this project.

**Comment by dsjoerg** [comment]
@gravelweb once you've got ggtrackerstack working in your dev environment, we can talk more specifically about how to make the time-related changes / fixes.   Let me know when you're ready?

The first design question is whether we care about preserving sc2reader / ggtracker correctness for pre-3.0 or pre-3.2 replays.  Of course, the work is trickier if we do.

**Comment by gravelweb** [comment]
@dsjoerg Sounds good. I still need to get settled in with my dev environment and work out the kinks. I'll probably take the rest of the week to do that.

**Comment by gravelweb** [comment]
@dsjoerg Wondering about version and expansion support for ggtacker.

1. Do WoL and HotS replays need to be supported? If the graphs change for LotV (like the chronoboost stat), the old graphs should be kept around if the detected expansion is one of those two.
2. I'm not sure if WoL and HotS were affected by the game time change in 3.0.0.
   - if they were not affected, should ggtracker continue to support the old game time?
   - if they were affected, should ggtracker have support for pre 3.0.0 replays?

**Comment by dsjoerg** [comment]
@gravelweb ideally we support all versions correctly.

However, I don't want the perfect to be the enemy of the good.  I figure that first we'll get things working for the current version, and break all previous versions.   Then, if there's interest, we can go back and add backwards compatibility.

**Comment by gravelweb** [comment]
@dsjoerg well put. something to consider, but not to prioritize. I suppose we should be able to start tackling this issue shortly

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#28
