### ISSUE TITLE
All activity is displayed in top right for 1v1

### ISSUE THREAD

**Issue by gravelweb** [dsjoerg/ggtracker#19]
The mini-map feature is not working properly for 1v1. All activity seems to be happening at the top right, outside the boundaries of the map. This doesn't seem to be an issue in 2v2.

**Comment by dsjoerg** [comment]
Whoa wow that is fascinating!  I had assumed that the bug affected all game modes.  The fact that it only happens in 1v1 is a massive clue and should make the bug a lot easier to fix. Thanks!

**Comment by dsjoerg** [comment]
OK, I've narrowed down the problem quite a bit (while streaming my session on twitch which has been fun :) )

The problem is that for certain maps (maybe all 1v1 maps?  not sure) the coordinate system as reported by replay.map.map_info.camera_left, replay.map.map_info.camera_* is no longer the same as the coordinate system used in the camera events.

Here's a session where I determined this:
```
was:sc2reader david$ python
Python 2.7.9 (default, Apr  7 2015, 07:58:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sc2reader
>>> replay = sc2reader.load_replay('/Users/David/Downloads/ggtracker_6586434.SC2Replay')
>>> replay.load_map()
>>> replay.map.map_info
<sc2reader.objects.MapInfo object at 0x101a1f310>
>>> replay.map.map_info.camera_right
134217728
>>> replay.map.map_info.camera_left
1768189509
>>> replay.map.map_info.camera_top
3489660928
>>> replay.map.map_info.camera_bottom
134245999
>>> camera_events = [e for e in replay.events if e.name == 'CameraEvent']
>>> len(camera_events)
3370
>>> camera_events[2500].x
44.25
>>> camera_events[2500].y
152.61328125
```

here's what a normal replay is supposed to be like:
```
>>> replay = sc2reader.load_replay('/Users/David/Downloads/ggtracker_6586262.SC2Replay')
yo
yo
yo
yo
yo
yo
yo
yo
yo
>>> replay.load_map()
>>> replay.map.map_info.camera_left
9
>>> replay.map.map_info.camera_right
175
>>> replay.map.map_info.camera_bottom
4
>>> replay.map.map_info.camera_top
168
>>> camera_events = [e for e in replay.events if e.name == 'CameraEvent']
>>> len(camera_events)
4828
>>> camera_events[2000].x
142.1796875
```

**Comment by dsjoerg** [comment]
So why are certain maps reporting really weird camera coordinates?   I have no clue at the moment.   Maybe there has been a change in the map data format.

In the absence of other ideas, maybe the sc2replaystats guy Anthony Martin will know.  I believe he is parsing some map information as well.  Also the code for SCELight is open source, András might know.  And I can always ask Bliz.

**Comment by dsjoerg** [comment]
The relevant function starts at https://github.com/GraylinKim/sc2reader/blob/master/sc2reader/objects.py#L478.   With Heroes of the Storm they easily could have added stuff to the map format which would throw off the reader.

**Comment by dsjoerg** [comment]
OK, asked Anthony, will post if he knows anything.

**Comment by dsjoerg** [comment]
Anthony doesnt have a way, he does it manually from the Galaxy Map Editor   TT    @gravelweb would you like to take a crack at it from here?   Two ways to go might be 1) look at the byte stream and maybe the correct bytes are obviously sitting there at a different offset, depending on which map version it is   2) look at SCELight / SC2Gears (both of which have code available) and see if either of those parses the map and if so, how.

**Comment by dsjoerg** [comment]
Anthony reminded me of another possibility; we could take a different approach completely and use some empirical magic to make a good guess.   We can use the camera events themselves to estimate the min-max range.

**Comment by gravelweb** [comment]
@dsjoerg I'm happy to look into it. Seems like a nice way to get my feet wet here :) Thanks for the details. Will check it out this evening.

**Comment by gravelweb** [comment]
This works well will followin maps:
 * Invader LE
 * Korhal Carnage
 * Frozen Temple
 * Ruins of Endion
 * Dusk Towers

*Unfortunately*, I'm having issues with Prion Terraces now. The symptoms are the same, but obviously the cause isn't, since my data dump is reporting seemingly correct camera info:

`02:15:05 python.1     | 2016-04-18 02:15:05  2939 WARNING  10 8 150 160`

I'll continue to investigate, but if you have any ideas off the top of your head.... happy to hear them!

**Comment by dsjoerg** [comment]
ok cool!  no ideas off the top of my head, basically what i do to diagnose these things is start in the client and work backward until i find bad data, and then look at the parsing code and see why its creating bad data.   i'll take a look at this monday or tuesday night and see what i can figure out.

that said, if ggtracker/sc2reader#11 works on the current ladder maps at least as well as the current code, then i'm inclined to push it into production and enjoy its benefits.   have you tried it on the ladder maps?  (not just 1v1)

**Comment by gravelweb** [comment]
I have tried all of the 1v1 ladder maps, since those were the ones affected... But I suppose it would be nice to verify that the other modes still work too 8)

**Comment by gravelweb** [comment]
1v1:
Newly Fixed:
 * Dusk Towers
 * Frozen Temple
 * Ruins of Endion
 * Ulrena
 * Invader LE
 * Korhal Carnage Knockout LE
Still Broken
 * Prion Terraces

2v2:
Still Working:
 * Infestation
 * Omicron
 * Sludge City
Newly Fixed:
 * Fields of death
 * Magma Mines
 * Distant Plane
 * Moebius Facility XX-1

3v3:
Not tested:
 * Avalon Labs
 * Backcountry
 * Doraelus Hills
 * Ice Cliffs
 * New Richmond
 * New Williamsberg
 * Slaying Field

4v4:
Not tested:
 * Abandoned Parish
 * Asper Mountain
 * Hidden Caves
 * Kimeran Refuge
 * Moebius Facility XX-1
 * Research Site JD-2
 * Void Zone

**Comment by gravelweb** [comment]
Looks pretty good :) I wanted to note, however, that this feature seems to break when reaching a certain part of the replay. I'm not sure if this is related to #16

**Comment by gravelweb** [comment]
The above reported issue is likely related to the timescale changes, as they do not seem to exist in production.

**Comment by gravelweb** [comment]
One more thing. The existing replays don't seem to get reparsed, so this fix will not affect existing replays, unless the user re-uploads them. Is that standard in ggtracker?

**Comment by dsjoerg** [comment]
@gravelweb we do map processing only once, the first time we see that map.  My plan was to manually somehow force map re-processing in production once you've got this working to your satisfaction.  For your dev testing purposes you can blow away the esdb_sc2_maps row to force a map re-process; however that will screw up any existing parsed esdb_matches rows that refer to the old map_id.

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#7
