### ISSUE TITLE
Show supply cap times

### ISSUE THREAD

**Issue by toff63** [dsjoerg/ggtracker#9]
Nicely show the periods when the play was supply cap and the total time during the game he was supply cap. This is a basic mistake for beginner. Fixing this issue will help player to improve

**Comment by dsjoerg** [comment]
By the way, if anyone wants to work on this, have a look at https://github.com/dsjoerg/ggpyjobs/blob/master/sc2parse/sc2reader_to_esdb.py#L196

That's where we walk through the tracker_events and pick out the PlayerStatsEvents.

**Comment by dsjoerg** [comment]
Or if you want a finer-grained look at whether a player is supply capped, you could walk through the finer-grained events of unit and building births and deaths.

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#33
